### ISSUE TITLE
Add a way to listen on all IPv4 interfaces

### ISSUE THREAD

**Issue by oliverpool** [AGWA/go-listener#1]
Hi, thanks for your amazing open-source work!

For usage with `snid`, I would like to run `-listen tcp4:443`, so that all IPv4 connections gets routed to my IPv6-only service.

I currently have to give the IPv4 addresses manually, but I would prefer having the possibility to have an "IP-less" config.

If you think that this is a valid usecase, I can make a PR to add a `tcp4` builtin (and eventually `tcp6`).

**Comment by AGWA** [comment]
I think the most intuitive way to support this is to make `tcp:0.0.0.0:443` work as expected - i.e. listen on all IPv4 interfaces.  (Currently it also listens on IPv6 interfaces.) I've created PR #2 to fix this. Do you see any issues with this approach?

**Comment by oliverpool** [comment]
I think this is a very elegant solution! (and worth adding some documentation :)

**Comment by AGWA** [comment]
All done, including docs. I've also released [snid v0.2.0](https://github.com/AGWA/snid/releases) which uses the new go-listener version.

**Comment by oliverpool** [comment]
Thank you so much!
